-- liquibase formatted sql

-- changeset Maria:3
CREATE TABLE pet
(
id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
chat_id bigint NOT NULL,
type varchar NOT NULL,
name varchar NOT NULL,
gender varchar NOT NULL,
age int NOT NULL,
sterile varchar NOT NULL,
feature varchar DEFAULT healthy,
feature_add text DEFAULT healthy,
PRIMARY KEY (id)
);