-- liquibase formatted sql

-- changeset csa21472001:1
CREATE TABLE nurserycatdogbot.photo
(
id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
filePath text,
fileSize bigint NOT NULL,
mediaType varchar,
data BYTEA,
report_id bigint REFERENCES nurserycatdogbot.report (id),
PRIMARY KEY (id));
