-- liquibase formatted sql

-- changeset Maria:5
CREATE TABLE nurserycatdogbot1.report
(
id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
chat_id bigint,
food text,
feel text,
behavior text,
date_time DATE,
foto_check BOOLEAN,
report_check BOOLEAN,
user_number bigint REFERENCES nurserycatdogbot1.users_contact_information (id),
PRIMARY KEY (id));


-- -- changeset Maria:51
-- Alter table nurserycatdogbot1.report
-- add constraint report_pk primary key (id)
--;