-- liquibase formatted sql

-- changeset Maria:5
CREATE TABLE nurserycatdogbot1.report
(
id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
chat_id bigint,
food text NOT NULL,
feel text NOT NULL,
behavior text NOT NULL,
date_time timestamp without time zone not null,
foto_check BOOLEAN,
report_check BOOLEAN,
user_number bigint REFERENCES nurserycatdogbot1.users_contact_information (phone),
PRIMARY KEY (id));